sequenceDiagram
  participant participant_collectObjectPaths as collectObjectPaths
  participant participant_collectStudioResponsePaths as collectStudioResponsePaths
  participant participant_readOwnProperty as readOwnProperty
  participant participant_resolveSchemaFields as resolveSchemaFields
  participant participant_resolveSchemaRef as resolveSchemaRef
  participant participant_resolveSchemaType as resolveSchemaType
  participant participant_resolveSingleSchemaType as resolveSingleSchemaType
  participant participant_resolveStudioSchemaValueMeta as resolveStudioSchemaValueMeta
  participant_collectStudioResponsePaths->>participant_resolveStudioSchemaValueMeta: resolveStudioSchemaValueMeta()
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaRef: resolveSchemaRef()
  participant_resolveSchemaRef->>participant_readOwnProperty: readOwnProperty()
  participant_readOwnProperty-->>participant_resolveSchemaRef: return
  participant_resolveSchemaRef->>participant_resolveSchemaRef: resolveSchemaRef()
  participant_resolveSchemaRef-->>participant_resolveSchemaRef: return
  participant_resolveSchemaRef-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaType: resolveSchemaType()
  participant_resolveSchemaType->>participant_resolveSingleSchemaType: resolveSingleSchemaType()
  participant_resolveSingleSchemaType-->>participant_resolveSchemaType: return
  participant_resolveSchemaType-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaFields: resolveSchemaFields()
  participant_resolveSchemaFields-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveStudioSchemaValueMeta: resolveStudioSchemaValueMeta()
  participant_resolveStudioSchemaValueMeta-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta-->>participant_collectStudioResponsePaths: return
  participant_collectStudioResponsePaths->>participant_collectObjectPaths: collectObjectPaths()
  participant_collectObjectPaths->>participant_resolveSchemaRef: resolveSchemaRef()
  participant_resolveSchemaRef-->>participant_collectObjectPaths: return
  participant_collectObjectPaths->>participant_resolveStudioSchemaValueMeta: resolveStudioSchemaValueMeta()
  participant_resolveStudioSchemaValueMeta-->>participant_collectObjectPaths: return
  participant_collectObjectPaths->>participant_collectObjectPaths: collectObjectPaths()
  participant_collectObjectPaths-->>participant_collectObjectPaths: return
  participant_collectObjectPaths-->>participant_collectStudioResponsePaths: return
