sequenceDiagram
  participant participant_createStudioUrlMediaAsset as createStudioUrlMediaAsset
  participant participant_normalizeStableHttpUrl as normalizeStableHttpUrl
  participant_createStudioUrlMediaAsset->>participant_normalizeStableHttpUrl: normalizeStableHttpUrl()
  participant_normalizeStableHttpUrl-->>participant_createStudioUrlMediaAsset: return
