sequenceDiagram
  participant participant_createStudioMediaAssetId as createStudioMediaAssetId
  participant participant_readOwnProperty as readOwnProperty
  participant_createStudioMediaAssetId->>participant_readOwnProperty: readOwnProperty()
  participant_readOwnProperty-->>participant_createStudioMediaAssetId: return
