sequenceDiagram
  participant participant_diagnoseStudioComponentBindings as diagnoseStudioComponentBindings
  participant participant_diagnostic as diagnostic
  participant participant_readOwnProperty as readOwnProperty
  participant_diagnoseStudioComponentBindings->>participant_readOwnProperty: readOwnProperty()
  participant_readOwnProperty-->>participant_diagnoseStudioComponentBindings: return
  participant_diagnoseStudioComponentBindings->>participant_diagnostic: diagnostic()
  participant_diagnostic-->>participant_diagnoseStudioComponentBindings: return
