sequenceDiagram
  participant participant_findNodeById as findNodeById
  participant_findNodeById->>participant_findNodeById: findNodeById()
  participant_findNodeById-->>participant_findNodeById: return
