sequenceDiagram
  participant participant_removeNodeFromTree as removeNodeFromTree
  participant participant_removeTreeNode as removeTreeNode
  participant_removeNodeFromTree->>participant_removeTreeNode: removeTreeNode()
  participant_removeTreeNode-->>participant_removeNodeFromTree: return
