sequenceDiagram
  participant participant_mapRecordEntries as mapRecordEntries
  participant participant_resolveStudioBindableProps as resolveStudioBindableProps
  participant_resolveStudioBindableProps->>participant_mapRecordEntries: mapRecordEntries()
  participant_mapRecordEntries-->>participant_resolveStudioBindableProps: return
