sequenceDiagram
  participant participant_resolveSchemaFields as resolveSchemaFields
  participant participant_resolveSchemaReference as resolveSchemaReference
  participant participant_resolveSchemaType as resolveSchemaType
  participant participant_resolveSingleSchemaType as resolveSingleSchemaType
  participant participant_resolveStudioSchemaValueMeta as resolveStudioSchemaValueMeta
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaReference: resolveSchemaReference()
  participant_resolveSchemaReference-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaType: resolveSchemaType()
  participant_resolveSchemaType->>participant_resolveSingleSchemaType: resolveSingleSchemaType()
  participant_resolveSingleSchemaType-->>participant_resolveSchemaType: return
  participant_resolveSchemaType-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveSchemaFields: resolveSchemaFields()
  participant_resolveSchemaFields-->>participant_resolveStudioSchemaValueMeta: return
  participant_resolveStudioSchemaValueMeta->>participant_resolveStudioSchemaValueMeta: resolveStudioSchemaValueMeta()
  participant_resolveStudioSchemaValueMeta-->>participant_resolveStudioSchemaValueMeta: return
