sequenceDiagram
  participant participant_mapRecordEntries as mapRecordEntries
  participant participant_resolveStudioBindableEvents as resolveStudioBindableEvents
  participant_resolveStudioBindableEvents->>participant_mapRecordEntries: mapRecordEntries()
  participant_mapRecordEntries-->>participant_resolveStudioBindableEvents: return
