sequenceDiagram
  participant participant_resolveStudioInstancePropertyFields as resolveStudioInstancePropertyFields
  participant participant_resolveStudioInstancePropertyGroups as resolveStudioInstancePropertyGroups
  participant_resolveStudioInstancePropertyGroups->>participant_resolveStudioInstancePropertyFields: resolveStudioInstancePropertyFields()
  participant_resolveStudioInstancePropertyFields-->>participant_resolveStudioInstancePropertyGroups: return
