sequenceDiagram
  participant participant_StudioApp as StudioApp
  participant participant_useFonts as useFonts
  participant_StudioApp->>participant_useFonts: useFonts()
  participant_useFonts-->>participant_StudioApp: return
