sequenceDiagram
  participant participant_StudioDashboard as StudioDashboard
  participant participant_useCallback as useCallback
  participant participant_useEffect as useEffect
  participant participant_useMemo as useMemo
  participant participant_useProjects as useProjects
  participant participant_useState as useState
  participant participant_useTemplateSummaries as useTemplateSummaries
  participant participant_useZoraTheme as useZoraTheme
  participant_StudioDashboard->>participant_useProjects: useProjects()
  participant_useProjects->>participant_useState: useState()
  participant_useState-->>participant_useProjects: return
  participant_useProjects->>participant_useCallback: useCallback()
  participant_useCallback-->>participant_useProjects: return
  participant_useProjects->>participant_useEffect: useEffect()
  participant_useEffect-->>participant_useProjects: return
  participant_useProjects-->>participant_StudioDashboard: return
  participant_StudioDashboard->>participant_useTemplateSummaries: useTemplateSummaries()
  participant_useTemplateSummaries->>participant_useState: useState()
  participant_useState-->>participant_useTemplateSummaries: return
  participant_useTemplateSummaries->>participant_useCallback: useCallback()
  participant_useCallback-->>participant_useTemplateSummaries: return
  participant_useTemplateSummaries->>participant_useEffect: useEffect()
  participant_useEffect-->>participant_useTemplateSummaries: return
  participant_useTemplateSummaries-->>participant_StudioDashboard: return
  participant_StudioDashboard->>participant_useZoraTheme: useZoraTheme()
  participant_useZoraTheme-->>participant_StudioDashboard: return
  participant_StudioDashboard->>participant_useState: useState()
  participant_useState-->>participant_StudioDashboard: return
  participant_StudioDashboard->>participant_useMemo: useMemo()
  participant_useMemo-->>participant_StudioDashboard: return
