sequenceDiagram
  participant participant_isStyleRecord as isStyleRecord
  participant participant_updateNodeInTree as updateNodeInTree
  participant_updateNodeInTree->>participant_isStyleRecord: isStyleRecord()
  participant_isStyleRecord-->>participant_updateNodeInTree: return
