sequenceDiagram
  participant participant_updateNodeInTree as updateNodeInTree
  participant participant_updateTreeNode as updateTreeNode
  participant_updateNodeInTree->>participant_updateTreeNode: updateTreeNode()
  participant_updateTreeNode-->>participant_updateNodeInTree: return
