sequenceDiagram
  participant participant_upsertStudioMediaAsset as upsertStudioMediaAsset
  participant participant_withOwnProperty as withOwnProperty
  participant_upsertStudioMediaAsset->>participant_withOwnProperty: withOwnProperty()
  participant_withOwnProperty-->>participant_upsertStudioMediaAsset: return
