sequenceDiagram
  participant participant_normalizeRel as normalizeRel
  participant participant_resolveRouteScreenFilePath as resolveRouteScreenFilePath
  participant participant_validateInsertRecipe as validateInsertRecipe
  participant participant_visit as visit
  participant_validateInsertRecipe->>participant_visit: visit()
  participant_visit->>participant_visit: visit()
  participant_visit->>participant_visit: visit()
  participant_visit->>participant_visit: visit()
  participant_visit->>participant_resolveRouteScreenFilePath: resolveRouteScreenFilePath()
  participant_resolveRouteScreenFilePath->>participant_normalizeRel: normalizeRel()
  participant_normalizeRel-->>participant_resolveRouteScreenFilePath: return
  participant_resolveRouteScreenFilePath-->>participant_visit: return
  participant_visit-->>participant_visit: return
  participant_visit-->>participant_visit: return
  participant_visit-->>participant_visit: return
  participant_visit-->>participant_validateInsertRecipe: return
