graph LR
  module_knip_config_ts["knip.config.ts"]
  module_paradox_config_ts["paradox.config.ts"]
  module_src_index_test_ts["src/index.test.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_index_test_ts --> module_src_index_ts
