graph LR
  module_knip_config_ts["knip.config.ts"]
  module_paradox_config_ts["paradox.config.ts"]
  module_src_index_test_ts["src/index.test.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_manifestState_public_test_ts["src/manifestState.public.test.ts"]
  module_src_manifestState_routes_test_ts["src/manifestState.routes.test.ts"]
  module_src_manifestState_test_ts["src/manifestState.test.ts"]
  module_src_manifestState_ts["src/manifestState.ts"]
  module_src_manifestSync_test_ts["src/manifestSync.test.ts"]
  module_src_manifestSync_ts["src/manifestSync.ts"]
  module_src_routeUtils_public_test_ts["src/routeUtils.public.test.ts"]
  module_src_routeUtils_test_ts["src/routeUtils.test.ts"]
  module_src_routeUtils_ts["src/routeUtils.ts"]
  module_src_index_test_ts --> module_src_index_ts
  module_src_manifestState_public_test_ts --> module_src_index_ts
  module_src_manifestState_public_test_ts --> module_src_manifestState_ts
  module_src_manifestState_routes_test_ts --> module_src_index_ts
  module_src_manifestState_routes_test_ts --> module_src_manifestState_ts
  module_src_manifestState_test_ts --> module_src_index_ts
  module_src_manifestState_test_ts --> module_src_manifestState_ts
  module_src_manifestState_ts --> module_src_index_ts
  module_src_manifestSync_test_ts --> module_src_index_ts
  module_src_manifestSync_test_ts --> module_src_manifestSync_ts
  module_src_manifestSync_ts --> module_src_index_ts
  module_src_routeUtils_public_test_ts --> module_src_routeUtils_ts
  module_src_routeUtils_test_ts --> module_src_routeUtils_ts
